name: First Workflow

on:
# Trigger the workflow when there is an issue is created
  issues:
    types: [opened]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step1
        run: |
                 echo "Step1 "

      - name: Step2
        run: |
                 echo "Step2 "
  cowsays:
  # run this job after the build job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: "Good morning London!!!!!"
          # Color of your cow
          color: red
          
