name: First Workflow

on:
# Trigger the workflow when there is an issue is created
  issues:
    types: [opened]
  workflow_dispatch: 

# define an environment variable with a string in it and pass it into one of the echo steps in job 1
env:
  MY_VAR: "Hello from the environment"
  OUR_VAR: "Testing another variable"
  
# pass MY_VAR into one of the echo steps in job 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step1
        run: |
                 echo "Step1 $MY_VAR"

      - name: Step2
        run: |
                 echo "Step2 "
  cowsays:
  # run this job after the build job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: "Good morning London!!!!!"
          # Color of your cow
          color: "red"
          
